regex:
  - md: "bold"
    html: "strong"
    pattern: "\\*\\*(.*?)\\*\\*"
    match: "<strong>\\1</strong>"

  - md: "italics"
    html: "em"
    pattern: "\\*(.*?)\\*"
    match: "<em>\\1</em>"

  - md: "links"
    html: "a"
    pattern: "\\[(.*?)\\]\\((.*?)\\)"
    match: '<a href="\2">\1</a>'
  
  - md: "code"
    html: "code"
    pattern: "```(?:[\\w+-]+\\s*)?\n?([\\s\\S]*?)```"
    match: "<pre><code>\\1</code></pre>"

replace:
  - md: "\\n"
    html: "<br>"

tags:
  - tag: "strong"
    attrs:
      classname: "testing"
      id: ""

  - tag: "em"
    attrs:
      classname: ""
      id: ""

  - tag: ""
    attrs:
      classname: ""
      id: ""
    pattern: r"\[(.*?)\]\((.*?)\)"
    match: r'<a href="\2">\1</a>'

  - tag: "code"
