parse_command_name: parse
command_prefix: "/"


# Leave channels uncommented to read all channels
# channels:
#   - channel_id: "1234567890"
#
args:
  - default_args: "--html --upload"
  parse:
    - name: "--html"
      type: "string"
      required: false
      description: "Parse MD to HTML"
    - name: "--md"
      type: "string"
      required: false
      description: "Parse HTML to MD"
    - name: "--message-id"
      type: "string"
      required: true
      description: "Message ID to parse content from. If none is provided, parses last message in the channel. If command is called in a reply, parses the reply."
    - name: "--upload"
      type: "string"
      required: false
      description: "Upload parsed content in a Discord reply. Discord file size limits apply. Filename defaults to {message ID}.html"
    - name: "--filename"
      type: "string"
      required: false
      description: "Parsed content filename, required for webhook."
    - name: "--webook"
      type: "string"
      required: false
      description: "Post content to a Webhook URL in JSON with 'content' as key and the parsed content as value, filename command is required" 
